# Generated by Django 4.2.15 on 2024-08-19 15:40

from django.db import migrations, models
import django.db.models.deletion
import giant_search.mixins
import cms.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ("tests", "0001_initial"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Selecting this option will publish this item"
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("position", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "hours",
                    models.CharField(
                        choices=[("full_time", "Full-Time"), ("part_time", "Part-Time")],
                        max_length=12,
                    ),
                ),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=30, blank=True)),
                (
                    "content",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        slotname="vacancy_content",
                        to="cms.placeholder",
                    ),
                ),
                (
                    "internal_link",
                    cms.models.fields.PageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_internal_links",
                        to="cms.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacancyCardsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("vacancy_count", models.IntegerField(default=3)),
                ("category", models.CharField(max_length=30, blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="VacancyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_cards",
                        to="tests.vacancycardsplugin",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_published": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_cards",
                        to="tests.vacancy",
                        verbose_name="Vacancy",
                    ),
                ),
            ],
            bases=(giant_search.mixins.SearchableMixin, models.Model),
        ),
    ]
